#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sac
Version  : 1.3
Release  : 2
URL      : https://repo1.maven.org/maven2/org/w3c/css/sac/1.3/sac-1.3.jar
Source0  : https://repo1.maven.org/maven2/org/w3c/css/sac/1.3/sac-1.3.jar
Source1  : https://repo1.maven.org/maven2/org/w3c/css/sac/1.3/sac-1.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : W3C
Requires: mvn-sac-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sac package.
Group: Data

%description data
data components for the mvn-sac package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/w3c/css/sac/1.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/w3c/css/sac/1.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/w3c/css/sac/1.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/w3c/css/sac/1.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar
/usr/share/java/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.pom
